## script to rank ASD genes based on proximity to SFARI1


library(tidyverse)
library(readxl)
library(dplyr)
library(data.table)
library(writexl)
library(tidyr)

options(dplyr.summarise.inform = FALSE)

`%!in%` <- Negate(`%in%`)

## define default datasets: 

## global distance table, as generated by the function:


file_dist_glob_SFARI1 <- './input_tables/GlobalDistance_SFARI1/file_dist_glob_SFARI1.rds'

readRDS(file_dist_glob_SFARI1) -> file_dist_glob_SFARI1


ProxPath_SFARI1_arrange_by_distance_table <- function (
    distance_file = file_dist_glob_SFARI1, ## output of
    Path_Length_threshold = 4,
    save_directory){
  
  default_max = ceiling(max(distance_file$Path_Score))
  
  distance_file%>%
    filter(Path_Length <= Path_Length_threshold )%>%
    group_by(QueryNode, EndPathways)%>%
    summarise(tot = n(), minimum_distance= min(Path_Score),  minimum_Length= min(Path_Length), resistance = 1/(sum(1/Path_Score))) -> summary.table.resistance
  
  merge( x= summary.table.resistance, y = distance_file, by = c('QueryNode', 'EndPathways')) -> dist.glob.filtered.pathway
  
  
  dist.glob.filtered.pathway%>%
    filter(Path_Length == minimum_Length)%>%
    filter(Path_Score == minimum_distance) -> dist.glob.filtered.pathway.proximity.filtered
  
  dist.glob.filtered.pathway.proximity.filtered%>%
    dplyr::select(QueryNode, EndNode, EndPathways, Path_Score)%>%
    arrange(Path_Score)%>%
    distinct(QueryNode, .keep_all = T) -> dist.glob.filtered.pathway.proximity.filtered
  
  xlsx::write.xlsx(dist.glob.filtered.pathway.proximity.filtered, paste0(save_directory,'distance_ALL_to_SFARI1.xlsx'), sheetName = '1', 
                   col.names = TRUE, row.names = FALSE)
  
  return (dist.glob.filtered.pathway.proximity.filtered)
}  

